(()=>{'use strict';
 const root=document.querySelector('.studio-opening'),convergence=document.querySelector('.studio-convergence');if(!root||!convergence)return;
 const first=root.querySelector('.studio-first'),second=root.querySelector('.studio-second'),specimen=root.querySelector('.studio-specimen'),field=root.querySelector('.specimen-field'),rows=[...root.querySelectorAll('.specimen-row')],focus=root.querySelector('.specimen-focus'),meter=root.querySelector('.studio-meter i'),words=[...convergence.querySelectorAll('.convergence-words>span')],result=convergence.querySelector('.convergence-result'),hint=convergence.querySelector('.convergence-top>span:last-child');
 const orbit=root.querySelector('.brand-orbit');
 const glow=document.createElement('div'),scan=document.createElement('div');glow.className='specimen-glow';scan.className='specimen-scan';glow.setAttribute('aria-hidden','true');scan.setAttribute('aria-hidden','true');specimen.prepend(glow);specimen.append(scan);
 const clamp=v=>Math.max(0,Math.min(1,v)),ease=v=>{v=clamp(v);return v*v*(3-2*v)},range=(v,a,b)=>ease((v-a)/(b-a)),reduced=()=>window.keppMotionReduced?window.keppMotionReduced():matchMedia('(prefers-reduced-motion: reduce)').matches;
 const offsets=words.map(()=>({x:0,y:0}));let drag=null,raf=0,last=0,hp=0,cp=0,ht=0,ct=0,heroStart=0,heroLength=1,wordStart=0,wordLength=1,mobile=false,enabled=true,px=0,py=0,x=0,y=0,heroVisible=true,wordsVisible=false,idle=0,travel=1,wordScale=1;
 function paint(t){raf=0;const dt=Math.min(50,t-(last||t-16));last=t;const factor=1-Math.exp(-dt/125);hp+=(ht-hp)*factor;cp+=(ct-cp)*factor;x+=(px-x)*factor;y+=(py-y)*factor;
  if(heroVisible){idle+=enabled?dt*.000009:0;const change=range(hp,mobile?.18:.30,mobile?.56:.68),out=range(hp,mobile?.64:.10,mobile?.86:.33),inside=mobile?0:range(hp,.40,.67);first.style.opacity=1-out;first.style.transform=`translate3d(0,${-out*35}px,0)`;first.inert=out>.75;second.style.opacity=inside;second.style.visibility=inside>.001?'visible':'hidden';second.style.transform=`translate3d(0,${(1-inside)*40}px,0)`;second.inert=inside<.75;second.setAttribute('aria-hidden',String(inside<.75));second.querySelector('a').tabIndex=inside>.75?0:-1;
   field.style.opacity=1-change;field.style.transform=`rotate(${-8+change*8}deg) scale(1.02)`;rows.forEach((row,i)=>{const drift=enabled?Math.sin(idle+i*.7)*5:0;row.style.transform=`translate3d(${(i%2?-14:0)+(i%2?1:-1)*(hp*28+drift)}%,0,0)`});focus.style.opacity=change;focus.style.transform=`translate3d(0,${(1-change)*30}px,0)`;glow.style.opacity=.3+change*.4;glow.style.transform=`translate3d(${x*16}%,${y*16}%,0) scale(${1+change*.1})`;scan.style.transform=`translate3d(0,${change*specimenHeight*.68}px,0) scaleX(${.3+change*.7})`;scan.style.opacity=Math.sin(change*Math.PI)*.45;specimen.style.transform=`perspective(1400px) rotateX(${-y*1.4}deg) rotateY(${x*2}deg)`;meter.style.transform=`scaleX(${hp})`;
  }
  if(orbit&&heroVisible){const morph=range(hp,.12,.65);orbit.style.transform=`rotate(${enabled?idle*45+hp*100:0}deg) scale(${1+morph*.45})`;orbit.style.opacity=.65-morph*.5}
  if(wordsVisible){const gather=range(cp,.12,.50),fade=1-range(cp,.43,.57),reveal=range(cp,.58,.76);words.forEach((word,i)=>{const points=[[-.25,-.22],[.24,-.19],[-.27,.16],[.22,.17],[0,.36]],point=points[i],offset=offsets[i];word.style.transform=`translate3d(${(point[0]*travel+offset.x)*(1-gather)}px,${(point[1]*wordScale+offset.y)*(1-gather)}px,0) rotate(${(i-2)*6*(1-gather)}deg) scale(${1-gather*.12})`;word.style.opacity=fade;word.style.pointerEvents=cp<.25?'auto':'none';word.tabIndex=cp<.25?0:-1});result.style.opacity=reveal;result.style.transform=`translate3d(0,${(1-reveal)*22}px,0) scale(${.97+reveal*.03})`;hint.style.opacity=1-range(cp,.1,.3);}
  if((enabled&&heroVisible&&hp<.7&&!document.hidden)||Math.abs(hp-ht)>.0001||Math.abs(cp-ct)>.0001||Math.abs(x-px)>.001||Math.abs(y-py)>.001)raf=requestAnimationFrame(paint);else last=0;
 }
 function wake(){if(!raf&&!document.hidden)raf=requestAnimationFrame(paint)}
 function update(){ht=enabled?clamp((scrollY-heroStart)/heroLength):0;ct=enabled?clamp((scrollY-wordStart)/wordLength):1;wake()}
 let specimenHeight=0;
 function measure(){mobile=innerWidth<=800;enabled=!reduced();root.classList.toggle('motion-ready',enabled);convergence.classList.toggle('motion-ready',enabled);heroStart=root.getBoundingClientRect().top+scrollY;heroLength=Math.max(1,root.offsetHeight-innerHeight);wordStart=convergence.getBoundingClientRect().top+scrollY;wordLength=Math.max(1,convergence.offsetHeight-innerHeight);specimenHeight=specimen.offsetHeight;travel=Math.min(innerWidth*.88,1000);wordScale=Math.min(innerHeight*.72,650);if(!enabled){hp=0;cp=1}update()}
 words.forEach((word,i)=>{word.setAttribute('role','button');word.setAttribute('aria-label',word.textContent+' — arrasta ou usa as setas');word.addEventListener('pointerdown',e=>{if(cp>=.25||drag)return;e.preventDefault();word.setPointerCapture(e.pointerId);drag={i,id:e.pointerId,x:e.clientX,y:e.clientY};word.classList.add('is-dragging')});word.addEventListener('pointermove',e=>{if(drag?.i!==i||drag.id!==e.pointerId)return;const rect=word.getBoundingClientRect();let dx=e.clientX-drag.x,dy=e.clientY-drag.y;dx=Math.max(10-rect.left,Math.min(innerWidth-10-rect.right,dx));dy=Math.max(70-rect.top,Math.min(innerHeight-85-rect.bottom,dy));offsets[i].x+=dx;offsets[i].y+=dy;drag.x=e.clientX;drag.y=e.clientY;wake()});const stop=()=>{drag=null;word.classList.remove('is-dragging')};word.addEventListener('pointerup',stop);word.addEventListener('pointercancel',stop);word.addEventListener('lostpointercapture',stop);word.addEventListener('keydown',e=>{const d={ArrowLeft:[-15,0],ArrowRight:[15,0],ArrowUp:[0,-15],ArrowDown:[0,15]}[e.key];if(d){e.preventDefault();offsets[i].x= Math.max(-travel*.2,Math.min(travel*.2,offsets[i].x+d[0]));offsets[i].y=Math.max(-80,Math.min(80,offsets[i].y+d[1]));wake()}if(e.key==='Home'){offsets[i]={x:0,y:0};wake()}})});
 specimen.addEventListener('pointermove',e=>{if(e.pointerType!=='mouse'||!enabled)return;const r=specimen.getBoundingClientRect();px=(e.clientX-r.left)/r.width-.5;py=(e.clientY-r.top)/r.height-.5;wake()},{passive:true});specimen.addEventListener('pointerleave',()=>{px=py=0;wake()});
 new IntersectionObserver(entries=>{for(const entry of entries){if(entry.target===root)heroVisible=entry.isIntersecting;else wordsVisible=entry.isIntersecting}wake()},{rootMargin:'80px'}).observe(root);
 new IntersectionObserver(([entry])=>{wordsVisible=entry.isIntersecting;wake()},{rootMargin:'80px'}).observe(convergence);
 addEventListener('scroll',update,{passive:true});addEventListener('resize',measure);addEventListener('pageshow',measure);addEventListener('load',measure);document.addEventListener('kepp-motion-change',measure);document.addEventListener('kepp-page-positioned',()=>{measure();hp=ht;cp=ct;wake()});matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',measure);document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(raf);raf=0;last=0}else wake()});measure();document.dispatchEvent(new Event('kepp-layout-ready'));
})();
